/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CombustivelRouteImport } from './routes/combustivel'
import { Route as EletricoRouteImport } from './routes/eletrico'
import { Route as EstacionamentoRouteImport } from './routes/estacionamento'
import { Route as ViagensRouteImport } from './routes/viagens'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CombustivelRoute = CombustivelRouteImport.update({
  id: '/combustivel',
  path: '/combustivel',
  getParentRoute: () => rootRouteImport,
} as any)
const EletricoRoute = EletricoRouteImport.update({
  id: '/eletrico',
  path: '/eletrico',
  getParentRoute: () => rootRouteImport,
} as any)
const EstacionamentoRoute = EstacionamentoRouteImport.update({
  id: '/estacionamento',
  path: '/estacionamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensRoute = ViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combustivel': typeof CombustivelRoute
  '/eletrico': typeof EletricoRoute
  '/estacionamento': typeof EstacionamentoRoute
  '/viagens': typeof ViagensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combustivel': typeof CombustivelRoute
  '/eletrico': typeof EletricoRoute
  '/estacionamento': typeof EstacionamentoRoute
  '/viagens': typeof ViagensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combustivel': typeof CombustivelRoute
  '/eletrico': typeof EletricoRoute
  '/estacionamento': typeof EstacionamentoRoute
  '/viagens': typeof ViagensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/combustivel' | '/eletrico' | '/estacionamento' | '/viagens'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/combustivel' | '/eletrico' | '/estacionamento' | '/viagens'
  id:
    | '__root__'
    | '/'
    | '/combustivel'
    | '/eletrico'
    | '/estacionamento'
    | '/viagens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CombustivelRoute: typeof CombustivelRoute
  EletricoRoute: typeof EletricoRoute
  EstacionamentoRoute: typeof EstacionamentoRoute
  ViagensRoute: typeof ViagensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combustivel': {
      id: '/combustivel'
      path: '/combustivel'
      fullPath: '/combustivel'
      preLoaderRoute: typeof CombustivelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eletrico': {
      id: '/eletrico'
      path: '/eletrico'
      fullPath: '/eletrico'
      preLoaderRoute: typeof EletricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estacionamento': {
      id: '/estacionamento'
      path: '/estacionamento'
      fullPath: '/estacionamento'
      preLoaderRoute: typeof EstacionamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens': {
      id: '/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof ViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CombustivelRoute: CombustivelRoute,
  EletricoRoute: EletricoRoute,
  EstacionamentoRoute: EstacionamentoRoute,
  ViagensRoute: ViagensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
